### ISSUE TITLE
Installed root certificate is not listed in "Certificate Trust Settings" due to iOS bug

### ISSUE THREAD

**Issue by ceoimon** [FiloSottile/mkcert#47]

**Comment by FiloSottile** [comment]
I'm not sure I understand the issue, can you provide some more details?

**Comment by ceoimon** [comment]
I'm trying to use the certificate on my iPhone (running iOS 11.4).

After I installed the certificate(rootCA.pem), it is not showing up in the (Settings > General > About > Certificate Trust Settings) and therefore I can't follow the [Enable full trust for root certificates](https://support.apple.com/en-nz/HT204477) instruction.

I am also able to reproduce the issue on an iPhone simulator:

![simulator screen shot - iphone x - 2018-07-13 at 10 29 38](https://user-images.githubusercontent.com/9743157/42669394-c5813c52-8687-11e8-901b-43df33cec553.png)
![simulator screen shot - iphone x - 2018-07-13 at 10 29 58](https://user-images.githubusercontent.com/9743157/42669400-d44cbac2-8687-11e8-8f23-0fad67b628bd.png)
![simulator screen shot - iphone x - 2018-07-13 at 10 30 07](https://user-images.githubusercontent.com/9743157/42669401-d4d11bd2-8687-11e8-8c4a-3add853f4314.png)

**Comment by J132134** [comment]
I have the same problem, too

**Comment by gedw99** [comment]
https://github.com/micromdm/scep

**Comment by tomodian** [comment]
having the same issue.

**Comment by FiloSottile** [comment]
🤬 https://forums.developer.apple.com/thread/89568

It's a bug in iOS, I'll work around it. Should manage to pull off reissuing the same CA without having to remake all certificates.

**Comment by FiloSottile** [comment]
Nope, fixing this will require reissuing the roots. I had an idea to misuse AuthorityKeyID (https://twitter.com/FiloSottile/status/1023564776834826240) but turns out we don't add one to our roots =(

**Comment by FiloSottile** [comment]
This should be fixed in the upcoming v1.0.1 version.

**If you have already used mkcert, you need to update it, and then regenerate the root.**

```
mkcert -uninstall
rm -r "$(mkcert -CAROOT)"
```

Skip the `-uninstall` step if you want existing certificates to keep working.

**Comment by FiloSottile** [comment]
Did you delete the root and regenerated it?

**Comment by shri3k** [comment]
I think this command essentially does that if I'm not mistaken.
```sh
rm -r "$(mkcert -CAROOT)"
```
I did however went and ran `mkcert -uninstall` too just for good measure.
I'm scratching my head and wanted to see if others got it working too. This is in iPhone XS Max (iOS 12.1) Emulator if it helps at all.

Also, one small request. Would it be possible to have `mkcert` display the current version it's running? I think I have the right binary in my `GOPATH` for mkcert. I checked the `src` and it had the latest commit from master branch but was unable to tell which version of binary I was running apart from checking the "modified date" of the binary.

I love the simplicity of this tool if I haven't mentioned that already. :smiley:

**Comment by Epho** [comment]
Anyone else still having issues? I just installed the latest mkcert and am unable to see the cert in "Certificate Trust Settings". I tried uninstalling, deleting the root, and regenerating, for good measure, but no dice.

![IMG_4EF636D49D4C-1](https://user-images.githubusercontent.com/1441652/71753178-96b86500-2e36-11ea-99c3-2efb38cacc04.jpeg)

**Comment by FiloSottile** [comment]
@Epho Please open a new issue and we'll look into it!
